const data = [
  {
    Region: "Bengaluru",
    Product: "Nutella Brownie Crumble Thick Shake",
    "Total Sales": 730.8,
    rank: 1,
  },
  {
    Region: "Bhubaneswar",
    Product: "Belgian Chocolate Thick Shake",
    "Total Sales": 19938.11,
    rank: 1,
  },
  {
    Region: "Bhubaneswar",
    Product: "Real Mango Fruit Thickshake",
    "Total Sales": 13042.09,
    rank: 2,
  },
  {
    Region: "Bhubaneswar",
    Product: "Choco Brownie Crumble Thick Shake",
    "Total Sales": 12290.37,
    rank: 3,
  },
  {
    Region: "Bhubaneswar",
    Product: "Nutella Brownie Crumble Thick Shake",
    "Total Sales": 6705.84,
    rank: 4,
  },
  {
    Region: "Bhubaneswar",
    Product: "Belgian Chocolate Milk Shake",
    "Total Sales": 4450.65,
    rank: 5,
  },
  {
    Region: "Bhubaneswar",
    Product: "Almond Mocha Thick Shake",
    "Total Sales": 4356.34,
    rank: 6,
  },
  {
    Region: "Bhubaneswar",
    Product: "Brownie Hotfudge Ice Cream Jar",
    "Total Sales": 3612.0,
    rank: 7,
  },
  {
    Region: "Bhubaneswar",
    Product: "Butterscotch Ice Cream Jar",
    "Total Sales": 3167.85,
    rank: 8,
  },
  {
    Region: "Bhubaneswar",
    Product: "Real Mango Fruit Milkshake",
    "Total Sales": 3131.03,
    rank: 9,
  },
  {
    Region: "Bhubaneswar",
    Product: "Kitkat Thick Shake",
    "Total Sales": 2837.88,
    rank: 10,
  },
  {
    Region: "Chennai",
    Product: "Choco Brownie Crumble Thick Shake",
    "Total Sales": 2611755.11,
    rank: 1,
  },
  {
    Region: "Chennai",
    Product: "Belgian Chocolate Thick Shake",
    "Total Sales": 2550998.03,
    rank: 2,
  },
  {
    Region: "Chennai",
    Product: "Nutella Brownie Crumble Thick Shake",
    "Total Sales": 1241138.77,
    rank: 3,
  },
  {
    Region: "Chennai",
    Product: "Ferrero Rocher Thick Shake",
    "Total Sales": 1141208.15,
    rank: 4,
  },
  {
    Region: "Chennai",
    Product: "Nutella Chocolate Blast Thick Shake",
    "Total Sales": 1001134.95,
    rank: 5,
  },
  {
    Region: "Chennai",
    Product: "Real Mango Fruit Thickshake",
    "Total Sales": 954098.53,
    rank: 6,
  },
  {
    Region: "Chennai",
    Product: "Kitkat Thick Shake",
    "Total Sales": 939246.51,
    rank: 7,
  },
  {
    Region: "Chennai",
    Product: "Belgian Chocolate Milk Shake",
    "Total Sales": 877371.9,
    rank: 8,
  },
  {
    Region: "Chennai",
    Product: "Crunchy Butterscotch Thick Shake",
    "Total Sales": 797098.16,
    rank: 9,
  },
  {
    Region: "Chennai",
    Product: "Oreo Nutella Thick Shake",
    "Total Sales": 724136.31,
    rank: 10,
  },
  {
    Region: "Delhi",
    Product: "Belgian Chocolate Thick Shake",
    "Total Sales": 18905.88,
    rank: 1,
  },
  {
    Region: "Delhi",
    Product: "Choco Brownie Crumble Thick Shake",
    "Total Sales": 12883.8,
    rank: 2,
  },
  {
    Region: "Delhi",
    Product: "Belgian Chocolate Milk Shake",
    "Total Sales": 11983.82,
    rank: 3,
  },
  {
    Region: "Delhi",
    Product: "Nutella Brownie Crumble Thick Shake",
    "Total Sales": 10292.98,
    rank: 4,
  },
  {
    Region: "Delhi",
    Product: "Ferrero Rocher Thick Shake",
    "Total Sales": 9562.0,
    rank: 5,
  },
  {
    Region: "Delhi",
    Product: "Nutella Chocolate Blast Thick Shake",
    "Total Sales": 7772.25,
    rank: 6,
  },
  {
    Region: "Delhi",
    Product: "Kitkat Thick Shake",
    "Total Sales": 5920.49,
    rank: 7,
  },
  {
    Region: "Delhi",
    Product: "Real Mango Fruit Thickshake",
    "Total Sales": 5461.7,
    rank: 8,
  },
  {
    Region: "Delhi",
    Product: "Strawberry Pink Penny Thick Shake",
    "Total Sales": 4610.65,
    rank: 9,
  },
  {
    Region: "Delhi",
    Product: "Crunchy Butterscotch Thick Shake",
    "Total Sales": 3290.94,
    rank: 10,
  },
  {
    Region: "Gurugram",
    Product: "Belgian Chocolate Thick Shake",
    "Total Sales": 11114.03,
    rank: 1,
  },
  {
    Region: "Gurugram",
    Product: "Choco Brownie Crumble Thick Shake",
    "Total Sales": 8553.16,
    rank: 2,
  },
  {
    Region: "Gurugram",
    Product: "Nutella Brownie Crumble Thick Shake",
    "Total Sales": 6258.01,
    rank: 3,
  },
  {
    Region: "Gurugram",
    Product: "Nutella Chocolate Blast Thick Shake",
    "Total Sales": 5565.55,
    rank: 4,
  },
  {
    Region: "Gurugram",
    Product: "Belgian Chocolate Milk Shake",
    "Total Sales": 3620.24,
    rank: 5,
  },
  {
    Region: "Gurugram",
    Product: "Choco Koffee Thick Shake",
    "Total Sales": 3609.81,
    rank: 6,
  },
  {
    Region: "Gurugram",
    Product: "Ferrero Rocher Thick Shake",
    "Total Sales": 3254.21,
    rank: 7,
  },
  {
    Region: "Gurugram",
    Product: "Strawberry Pink Penny Thick Shake",
    "Total Sales": 3089.5,
    rank: 8,
  },
  {
    Region: "Gurugram",
    Product: "Kitkat Thick Shake",
    "Total Sales": 2668.76,
    rank: 9,
  },
  {
    Region: "Gurugram",
    Product: "Oreo Nutella Thick Shake",
    "Total Sales": 2400.84,
    rank: 10,
  },
  {
    Region: "Hanumakonda",
    Product: "Belgian Chocolate Thick Shake",
    "Total Sales": 29583.14,
    rank: 1,
  },
  {
    Region: "Hanumakonda",
    Product: "Choco Brownie Crumble Thick Shake",
    "Total Sales": 24934.58,
    rank: 2,
  },
  {
    Region: "Hanumakonda",
    Product: "Nutella Brownie Crumble Thick Shake",
    "Total Sales": 24715.5,
    rank: 3,
  },
  {
    Region: "Hanumakonda",
    Product: "Kitkat Thick Shake",
    "Total Sales": 18279.2,
    rank: 4,
  },
  {
    Region: "Hanumakonda",
    Product: "Ferrero Rocher Thick Shake",
    "Total Sales": 17743.2,
    rank: 5,
  },
  {
    Region: "Hanumakonda",
    Product: "Oreo Nutella Thick Shake",
    "Total Sales": 10351.25,
    rank: 6,
  },
  {
    Region: "Hanumakonda",
    Product: "Nutella Chocolate Blast Thick Shake",
    "Total Sales": 9024.09,
    rank: 7,
  },
  {
    Region: "Hanumakonda",
    Product: "Crunchy Butterscotch Thick Shake",
    "Total Sales": 7358.55,
    rank: 8,
  },
  {
    Region: "Hanumakonda",
    Product: "Real Mango Fruit Thickshake",
    "Total Sales": 6718.56,
    rank: 9,
  },
  {
    Region: "Hanumakonda",
    Product: "Caramel Butterscotch Thick Shake",
    "Total Sales": 6179.73,
    rank: 10,
  },
  {
    Region: "Hyderabad",
    Product: "Belgian Chocolate Thick Shake",
    "Total Sales": 11118073.78,
    rank: 1,
  },
  {
    Region: "Hyderabad",
    Product: "Choco Brownie Crumble Thick Shake",
    "Total Sales": 10209015.24,
    rank: 2,
  },
  {
    Region: "Hyderabad",
    Product: "Nutella Brownie Crumble Thick Shake",
    "Total Sales": 6489005.46,
    rank: 3,
  },
  {
    Region: "Hyderabad",
    Product: "Ferrero Rocher Thick Shake",
    "Total Sales": 5254423.15,
    rank: 4,
  },
  {
    Region: "Hyderabad",
    Product: "Kitkat Thick Shake",
    "Total Sales": 4135055.31,
    rank: 5,
  },
];

export { data };
