const ThkShkBranchTrans = {
  ProList: [
    {
      BranchName: "Kukatpally Phase 13",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 908.6,
    },
    {
      BranchName: "7004-TTSF - Satya Niketan",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 44440.78,
    },
    {
      BranchName: "Qcity Hyderabad",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 337151.3,
    },
    {
      BranchName: "1411-Manikonda",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 290933.63,
    },
    {
      BranchName: "1406-Thickshake Events",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 262811,
    },
    {
      BranchName: "GVK Banjara Hills",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 533915.74,
    },
    {
      BranchName: "5401-Ashok Nagar",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 219518.34,
    },
    {
      BranchName: "VR Mall",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 371318.9,
    },
    {
      BranchName: "Chandanagar New",
      Year: 2023,
      Month: "October",
      TotalPaidAmount: 0,
    },
    {
      BranchName: "Inorbit Mall - Madhapur",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 552018.33,
    },
    {
      BranchName: "Himayat Nagar",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 332355.4,
    },
    {
      BranchName: "1418-Kompally",
      Year: " Terminal 2.0",
      Month: 2024,
      TotalPaidAmount: "January",
      Column5: 417444.52,
    },
    {
      BranchName: "1505-Jubilee Hills (Rice Bowl)",
      Year: 2023,
      Month: "November",
      TotalPaidAmount: 0,
    },
    {
      BranchName: "Asian Mosapet",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 130014.8,
    },
    {
      BranchName: "1406-Thickshake Events",
      Year: 2023,
      Month: "January",
      TotalPaidAmount: 0,
    },
    {
      BranchName: "2003-Marathalli",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 555.56,
    },
    {
      BranchName: "Marina Mall (Chennai)",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 68921,
    },
    {
      BranchName: "HI Tension Line - Kondapur",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 475320.94,
    },
    {
      BranchName: "Anna Nagar",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 223598,
    },
    {
      BranchName: "1403-100ft Road Madhapur",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 6104.52,
    },
    {
      BranchName: "Tadepalli.AP",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 172869.6,
    },
    {
      BranchName: "TTSF- Greater Kailash",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 603.96,
    },
    {
      BranchName: "Qcity Hyderabad",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 3000.61,
    },
    {
      BranchName: "DD Colony",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 1044.5,
    },
    {
      BranchName: "Raichandani Mall Kompally",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 249873.48,
    },
    {
      BranchName: "5003-Perungudi",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 233372.71,
    },
    {
      BranchName: "Dilsukhnagar",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 331962.48,
    },
    {
      BranchName: "HYDERABAD/L.B NAGAR",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 611436.3,
    },
    {
      BranchName: "Ranchi",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 179787,
    },
    {
      BranchName: "1403-100ft Road Madhapur",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 274616.87,
    },
    {
      BranchName: "Tadepalli.AP",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 240,
    },
    {
      BranchName: "Sai Nath Colony -100 Ft. Ring Road",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 66785.8,
    },
    {
      BranchName: "2011-Mahadevpura",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 579.6,
    },
    {
      BranchName: "Sainikpuri",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 258739.69,
    },
    {
      BranchName: "1504-Himayath Nagar (Rice Bowl)",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 657380.35,
    },
    {
      BranchName: "Hyderabad/Nizampet",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 71500,
    },
    {
      BranchName: "1505-Jubilee Hills (Rice Bowl)",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 6188,
    },
    {
      BranchName: "Himayat Nagar",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 233,
    },
    {
      BranchName: "5405-GST Road",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 139388.9,
    },
    {
      BranchName: "Gopannapalli New",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 110964.83,
    },
    {
      BranchName: "5403-T. Nagar",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 251178.93,
    },
    {
      BranchName: "NAD Road - Visakhapatnam",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 97642,
    },
    {
      BranchName: "8004 - Hawker Street Ambience Mall",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 11737,
    },
    {
      BranchName: "1408-Khammam",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 168956.69,
    },
    {
      BranchName: "The Thickshake Factory - Madurai",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 497363.6,
    },
    {
      BranchName: "1418-Kompally",
      Year: " Terminal 2.0",
      Month: 2024,
      TotalPaidAmount: "February",
      Column5: 236,
    },
    {
      BranchName: "R K Beach Road - Visakhapatnam",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 268984,
    },
    {
      BranchName: "Moti Nagar_Cloud",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 108541.87,
    },
    {
      BranchName: "L&T Punjagutta",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 545631.5,
    },
    {
      BranchName: "2012-Banashankari",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 763,
    },
    {
      BranchName: "2005-Sarjapur",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 2288.7,
    },
    {
      BranchName: "5401-Ashok Nagar",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 459.59,
    },
    {
      BranchName: "Erramanzil Hyderabad",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 217753,
    },
    {
      BranchName: "Kukatpally Phase 13",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 187538.82,
    },
    {
      BranchName: "1419-AS Rao Nagar",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 864,
    },
    {
      BranchName: "8003 Delhi Warehouse",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 22590,
    },
    {
      BranchName: "1412-S.R.Nagar",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 163514.45,
    },
    {
      BranchName: "1505-Jubilee Hills (Rice Bowl)",
      Year: 2023,
      Month: "December",
      TotalPaidAmount: 451,
    },
    {
      BranchName: "Last Exit Drive - In Sultanpur",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 1082,
    },
    {
      BranchName: "Hyderabad Atrium.GACH",
      Year: 2023,
      Month: "December",
      TotalPaidAmount: 576,
    },
    {
      BranchName: "1401-Syala - ThickShake",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 732546,
    },
    {
      BranchName: "Chandanagar New",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 188338.08,
    },
    {
      BranchName: "Bachupally New",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 137352.35,
    },
    {
      BranchName: "7003 - NSP Pacific Mall",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 126257.79,
    },
    {
      BranchName: "Sarath City Mall 4th Floor",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 749212,
    },
    {
      BranchName: "1508-West Maredpally (RBBB)",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 56642,
    },
    {
      BranchName: "Ashoka One Mall",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 176771,
    },
    {
      BranchName: "1004-Kukatpally",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 867.84,
    },
    {
      BranchName: "Asian Satyam Mall",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 85521,
    },
    {
      BranchName: "HI Tension Line - Kondapur",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 4151,
    },
    {
      BranchName: "MIDWAY Drive-in",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 264047.9,
    },
    {
      BranchName: "5003-Perungudi",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 1349,
    },
    {
      BranchName: "Lakdikapul.LDK",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 4500.4,
    },
    {
      BranchName: "HYDERABAD/L.B NAGAR",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 1578.6,
    },
    {
      BranchName: "Sarath City Mall Kothaguda",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 654817,
    },
    {
      BranchName: "Siripuram",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 253635,
    },
    {
      BranchName: "CMR Vizag",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 308003.91,
    },
    {
      BranchName: "1006-Abids N",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 1163,
    },
    {
      BranchName: "1504-Himayath Nagar (Rice Bowl)",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 3914,
    },
    {
      BranchName: "Indira Nagar - Hyderabad",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 184489,
    },
    {
      BranchName: "1407-West Maredpally (TTSF)",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 2212,
    },
    {
      BranchName: "Madipakkam",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 146457,
    },
    {
      BranchName: "GAMA & B Nexus Mall Hyderabad",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 621312.77,
    },
    {
      BranchName: "8001-GVM Mall Greater Noida",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 61198.4,
    },
    {
      BranchName: "Habsiguda",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 106608.84,
    },
    {
      BranchName: "5403-T. Nagar",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 1958.66,
    },
    {
      BranchName: "Film Nagar",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 3058,
    },
    {
      BranchName: "1413-Hanumakonda",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 238441.53,
    },
    {
      BranchName: "1503-Habsiguda (Rice Bowl)",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 38622.48,
    },
    {
      BranchName: "TSF - GSM Mall",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 289085.4,
    },
    {
      BranchName: "Madurawada",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 27938,
    },
    {
      BranchName: "1419-AS Rao Nagar",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 221232.94,
    },
    {
      BranchName: "1414- Suncity",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 236111.08,
    },
    {
      BranchName: "Siripuram",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 752,
    },
    {
      BranchName: "1020-Syala Dessert Factory",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 139,
    },
    {
      BranchName: "L&T Metro",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 272661,
    },
    {
      BranchName: "1414- Suncity",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 1211.4,
    },
    {
      BranchName: "Last Exit Drive - In Sultanpur",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 36960,
    },
    {
      BranchName: "1407-West Maredpally (TTSF)",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 275758.55,
    },
    {
      BranchName: "Lakdikapul.LDK",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 208212.5,
    },
    {
      BranchName: "Bhubaneswar",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 113230,
    },
    {
      BranchName: "1506-Kukatpally (Rice Bowl)",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 35072,
    },
    {
      BranchName: "Film Nagar",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 120667.22,
    },
    {
      BranchName: "DSL Virtue Mall",
      Year: " Uppal",
      Month: 2024,
      TotalPaidAmount: "January",
      Column5: 509365,
    },
    {
      BranchName: "1003-Toli chowki",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 248,
    },
    {
      BranchName: "Phoenix Mall Guntur",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 175505,
    },
    {
      BranchName: "1507-SR Nagar (Rice Bowl)",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 84809.3,
    },
    {
      BranchName: "1505-Jubilee Hills (Rice Bowl)",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 1160948.61,
    },
    {
      BranchName: "1401-Syala - ThickShake",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 2353,
    },
    {
      BranchName: "Bhel",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 13328,
    },
    {
      BranchName: "DD Colony",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 167915.1,
    },
    {
      BranchName: "Ramachandra Nagar - Vijayawada",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 10097,
    },
    {
      BranchName: "LULU Mall",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 637805,
    },
    {
      BranchName: "1003-Toli chowki",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 234343.99,
    },
    {
      BranchName: "Moti Nagar_Cloud",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 3951.68,
    },
    {
      BranchName: "1420 - Value Zone Patancheru",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 151819,
    },
    {
      BranchName: "7002-Ardee Mall-Delhi",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 105158.2,
    },
    {
      BranchName: "Infinity Drive-In",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 6614.05,
    },
    {
      BranchName: "1505-Jubilee Hills (Rice Bowl)",
      Year: 2022,
      Month: "November",
      TotalPaidAmount: 456,
    },
    {
      BranchName: "Satya 5 Food Court",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 76958.15,
    },
    {
      BranchName: "1411-Manikonda",
      Year: 2024,
      Month: "February",
      TotalPaidAmount: 664.8,
    },
    {
      BranchName: "The Thickshake Factory - Porur",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 142499,
    },
    {
      BranchName: "Hyderabad Kokapet",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 126572.54,
    },
    {
      BranchName: "Hyderabad Atrium.GACH",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 422794,
    },
    {
      BranchName: "1005-Gachibowli",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 1021,
    },
    {
      BranchName: "2009-New BEL Road Cloud",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 474,
    },
    {
      BranchName: "Aurabindo Galaxy Hi-Tech City",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 48886,
    },
    {
      BranchName: "Necklace Mall",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 201955,
    },
    {
      BranchName: "Ice and Fire Drive In",
      Year: 2024,
      Month: "January",
      TotalPaidAmount: 59130,
    },
  ],
};
export { ThkShkBranchTrans };
